### ISSUE TITLE
#33 프로필 보관함에서 특정 마이프로필 삭제 api 구현

### ISSUE THREAD

**Issue by Byun-Sung-Ho** [UMC-AboutMe/AboutMe-BE#33]
## 📝 개요
- 프로필 보관함에서 특정 마이프로필 삭제 api 구현

## ✔️ To-Do
- [ ] 프로필 보관함에서 특정 마이프로필 삭제 api 구현

## 👀 ETC
- 참고자료 등 기타 내용 작성

**Comment by ranunclulus** [comment]
Assignees랑 Project 할당해 주세요
